# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbbf6efd814aa986bb4fdec4c943293cfbc70fd7ffca4793c67c73976afc48842ee648e4b4a4147ca591956051ea85c45d367d23951f1c23ea721284cfeeccda

test:
  secret_key_base: f6e948614e7b2a01c68a7f913c6f9a85af2238833cf12c35547be206b027c0428d5a27088d972d5f67d42ad955c0903617a0f2d9bf0c5782ceca01b4dc8d2b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
